Print("======================================");
kill(all);
print("Q 5.7");

powerdisp:false;

Y:sum(c[m]*x^m,m,0,inf);
Y1:sum(m*c[m]*x^(m-1),m,1,inf);
Y2:sum(m*(m-1)*c[m]*x^(m-2),m,2,inf);

eq:(1-x)*Y1-Y;
expand(%);
intosum(%);
factorsum(%);

changevar(part(%,1),k-m,k,m)+changevar(part(%,2),k-m,k,m)+changevar(part(%,3),k-m+1,k,m);
intosum(%);
sumcontract(%);
LHS:factorsum(%);
RHS:0;
REC:coeff(part(LHS,1,1),x,k);
CON:part(LHS,2)+part(LHS,3);
makelist(subst(k=m,REC)=0,m,1,6);
append(%,[CON=0]);
SOL:linsolve(%,makelist(c[k],k,1,7));
c[0]+subst(%,sum(c[k]*x^k,k,1,7));

kill(all);
eq:'diff(y,x)*(1-x)=y;
ode2(eq,y,x);


Print("======================================");
kill(all);
print("Q 5.8");

powerdisp:false;

Y:sum(c[m]*x^m,m,0,inf);
Y1:sum(m*c[m]*x^(m-1),m,1,inf);
Y2:sum(m*(m-1)*c[m]*x^(m-2),m,2,inf);

eq:x*Y1-3*Y-R;
expand(%);
intosum(%);
factorsum(%);

changevar(part(%,1),k-m,k,m)+changevar(part(%,2),k-m,k,m)+changevar(part(%,3),k-m,k,m); 
intosum(%);
sumcontract(%);
LHS:factorsum(%);
RHS:0;
REC:coeff(part(LHS,2,1),x,k);
CON:part(LHS,1)+part(LHS,3);
makelist(subst(k=m,REC)=0,m,1,6);
append(%,[CON=0]);
SOL:linsolve(%,makelist(c[k],k,1,7));
c[0]+subst(%,sum(c[k]*x^k,k,1,7));

kill(all);
eq:x*'diff(y,x)-3*y=k;
ode2(eq,y,x);


Print("======================================");
kill(all);
print("Q 5.9");

powerdisp:false;

Y:sum(c[m]*x^m,m,0,inf);
Y1:sum(m*c[m]*x^(m-1),m,1,inf);
Y2:sum(m*(m-1)*c[m]*x^(m-2),m,2,inf);

eq:Y2-Y1+x*Y;
expand(%);
intosum(%);
factorsum(%);

changevar(part(%,1),k-m-1,k,m)+changevar(part(%,2),k-m+1,k,m)+changevar(part(%,3),k-m+2,k,m);
intosum(%);
sumcontract(%);
LHS:factorsum(%);
RHS:0;
REC:coeff(part(LHS,1,1),x,k);
CON:part(LHS,2)+part(LHS,3);
makelist(subst(k=m,REC)=0,m,1,5);
append(%,[CON=0]);
SOL:linsolve(%,makelist(c[k],k,2,7));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
1+subst(%,sum(c[k]*x^k,k,2,7));
subst([c[0]=0,c[1]=1],SOL)$
x+subst(%,sum(c[k]*x^k,k,2,7));
powerdisp:false$



Print("======================================");
kill(all);
print("Q 5.10");

powerdisp:false;

Y:sum(c[m]*x^m,m,0,inf);
Y1:sum(m*c[m]*x^(m-1),m,1,inf);
Y2:sum(m*(m-1)*c[m]*x^(m-2),m,2,inf);

eq:Y2-Y1-x*Y;
expand(%);
intosum(%);
factorsum(%);

changevar(part(%,1),k-m-1,k,m)+changevar(part(%,2),k-m+1,k,m)+changevar(part(%,3),k-m+2,k,m);
intosum(%);
sumcontract(%);
LHS:factorsum(%);
RHS:0;
REC:coeff(part(LHS,1,1),x,k);
CON:part(LHS,2)+part(LHS,3);
makelist(subst(k=m,REC)=0,m,1,5);
append(%,[CON=0]);
SOL:linsolve(%,makelist(c[k],k,2,7));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
1+subst(%,sum(c[k]*x^k,k,2,7));
subst([c[0]=0,c[1]=1],SOL)$
x+subst(%,sum(c[k]*x^k,k,2,7));
powerdisp:false$


Print("======================================");
kill(all);
print("Q 5.11");

powerdisp:false;

Y:sum(c[m]*x^m,m,0,inf);
Y1:sum(m*c[m]*x^(m-1),m,1,inf);
Y2:sum(m*(m-1)*c[m]*x^(m-2),m,2,inf);

eq:Y2-Y1-x^2*Y;
expand(%);
intosum(%);
factorsum(%);

changevar(part(%,1),k-m-2,k,m)+changevar(part(%,2),k-m+1,k,m)+changevar(part(%,3),k-m+2,k,m);
intosum(%);
sumcontract(%);
LHS:factorsum(%);
RHS:0;
REC:coeff(part(LHS,1,1),x,k);
part(LHS,2)+part(LHS,3);
kk:expand(%);
RECA:coeff(part(kk,1),x,1)+coeff(part(kk,2),x,1);
CON:part(kk,3)+part(kk,4);
makelist(subst(k=m,REC)=0,m,2,5);
append(%,[CON=0]);
append(%,[RECA=0]);
SOL:linsolve(%,makelist(c[k],k,2,7));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
1+subst(%,sum(c[k]*x^k,k,2,7));
subst([c[0]=0,c[1]=1],SOL)$
x+subst(%,sum(c[k]*x^k,k,2,7));
powerdisp:false$



Print("======================================");
kill(all);
print("Q 5.12");

powerdisp:false;

Y:sum(c[m]*x^m,m,0,inf);
Y1:sum(m*c[m]*x^(m-1),m,1,inf);
Y2:sum(m*(m-1)*c[m]*x^(m-2),m,2,inf);

eq:Y2-x*Y1-x^2*Y;
expand(%);
intosum(%);
factorsum(%);

changevar(part(%,1),k-m-2,k,m)+changevar(part(%,2),k-m,k,m)+changevar(part(%,3),k-m+2,k,m);
intosum(%);
sumcontract(%);
LHS:factorsum(%);
RHS:0;
REC:coeff(part(LHS,1,1),x,k);
RECA:coeff(part(LHS,2),x,1);
CON:part(LHS,3);
makelist(subst(k=m,REC)=0,m,2,5);
append(%,[CON=0]);
append(%,[RECA=0]);
SOL:linsolve(%,makelist(c[k],k,2,7));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
1+subst(%,sum(c[k]*x^k,k,2,7));
subst([c[0]=0,c[1]=1],SOL)$
x+subst(%,sum(c[k]*x^k,k,2,7));
powerdisp:false$



Print("======================================");
kill(all);
print("Q 5.13");

powerdisp:false;

Y:sum(c[m]*x^m,m,0,inf);
Y1:sum(m*c[m]*x^(m-1),m,1,inf);
Y2:sum(m*(m-1)*c[m]*x^(m-2),m,2,inf);

eq:(1-x^2)*Y2-2*x*Y1+6*Y;
expand(%);
intosum(%);
factorsum(%);

changevar(part(%,1),k-m,k,m)+changevar(part(%,2),k-m,k,m)+changevar(part(%,3),k-m,k,m)+changevar(part(%,4),k-m+2,k,m);
intosum(%);
sumcontract(%);
LHS:factorsum(%);
RHS:0;
REC:coeff(part(LHS,1,1),x,k);
RECA:coeff(part(LHS,2),x,1);
CON:part(LHS,3)+part(LHS,4);
makelist(subst(k=m,REC)=0,m,2,5);
append(%,[CON=0]);
append(%,[RECA=0]);
SOL:linsolve(%,makelist(c[k],k,2,7));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
1+subst(%,sum(c[k]*x^k,k,2,7));
subst([c[0]=0,c[1]=1],SOL)$
x+subst(%,sum(c[k]*x^k,k,2,7));
powerdisp:false$



Print("======================================");
kill(all);
print("Q 5.16");

powerdisp:false;

Y:sum(c[m]*x^m,m,0,inf);
Y1:sum(m*c[m]*x^(m-1),m,1,inf);
Y2:sum(m*(m-1)*c[m]*x^(m-2),m,2,inf);

eq:Y1+9*Y;
expand(%);
intosum(%);
factorsum(%);

changevar(part(%,1),k-m,k,m)+changevar(part(%,2),k-m+1,k,m);
intosum(%);
sumcontract(%);
LHS:factorsum(%);
RHS:0;
REC:coeff(part(LHS,1),x,k);

makelist(subst(k=m,REC)=0,m,1,6);
append(%,[c[1]+9*c[0]=2]);
SOL:linsolve(%,makelist(c[k],k,1,7)); 
solk:subst(%,sum(c[k]*x^k,k,0,3));

solve(ev(solk,x=0)=6,c[0]);
solkk:ev(solk,x=1,c[0]=6);
powerdisp:false$


Print("======================================");
kill(all);
print("Q 5.17");

powerdisp:false;

Y:sum(c[m]*x^m,m,0,inf);
Y1:sum(m*c[m]*x^(m-1),m,1,inf);
Y2:sum(m*(m-1)*c[m]*x^(m-2),m,2,inf);

eq:Y2+4*x*Y1+1*Y;
expand(%);
intosum(%);
factorsum(%);

changevar(part(%,1),k-m,k,m)+changevar(part(%,2),k-m,k,m)+changevar(part(%,3),k-m+2,k,m);
intosum(%);
sumcontract(%);
LHS:factorsum(%);
RHS:0;
REC:coeff(part(LHS,1,1),x,k);
CON:part(LHS,2)+part(LHS,3);
makelist(subst(k=m,REC)=0,m,1,5);
append(%,[CON=0]);
SOL:linsolve(%,makelist(c[k],k,2,7));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
y0:1+subst(%,sum(c[k]*x^k,k,2,4));
subst([c[0]=0,c[1]=1],SOL)$
y1:x+subst(%,sum(c[k]*x^k,k,2,4));

y:a0*y0+a1*y1;
eq1:ev(y,x=0)=1;
eq2:diff(y,x);
eq3:ev(eq2,x=0)=1;

yy:ev(y,a0=1,a1=1);
ev(yy,x=0.1);

powerdisp:false$

Print("======================================");
kill(all);
print("Q 5.18");

powerdisp:false;

Y:sum(c[m]*x^m,m,0,inf);
Y1:sum(m*c[m]*x^(m-1),m,1,inf);
Y2:sum(m*(m-1)*c[m]*x^(m-2),m,2,inf);

eq:(1-x^2)*Y2-2*x*Y1+12*Y;
expand(%);
intosum(%);
factorsum(%);

changevar(part(%,1),k-m,k,m)+changevar(part(%,2),k-m,k,m)+changevar(part(%,3),k-m,k,m)+changevar(part(%,4),k-m+2,k,m);
intosum(%);
sumcontract(%);
LHS:factorsum(%);
RHS:0;
REC:coeff(part(LHS,1,1),x,k);
RECA:coeff(part(LHS,2),x,1);
CON:part(LHS,3)+part(LHS,4);
makelist(subst(k=m,REC)=0,m,2,5);
append(%,[CON=0]);
append(%,[RECA=0]);
SOL:linsolve(%,makelist(c[k],k,2,7));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
y0:1+subst(%,sum(c[k]*x^k,k,2,7));
subst([c[0]=0,c[1]=1],SOL)$
y1:x+subst(%,sum(c[k]*x^k,k,2,7));

yy:0*y0-3/2*y1;
ev(yy,x=0.5);
powerdisp:false$




Print("======================================");
kill(all);
print("Q 5.19");

powerdisp:false;

Y:sum(c[m]*x^m,m,0,inf);
Y1:sum(m*c[m]*x^(m-1),m,1,inf);
Y2:sum(m*(m-1)*c[m]*x^(m-2),m,2,inf);

eq:(x-4)*Y1-x*Y;
expand(%);
intosum(%);
factorsum(%);

changevar(part(%,1),k-m-1,k,m)+changevar(part(%,2),k-m,k,m)+changevar(part(%,3),k-m+1,k,m);
intosum(%);
sumcontract(%);
factorsum(%);
LHS:intosum(%);
REC:coeff(part(LHS,1,1),x,k);
CON:part(LHS,2);
makelist(subst(k=m,REC)=0,m,1,4);
append(%,[CON=0]);
SOL:linsolve(%,makelist(c[k],k,1,5));
powerdisp:true$
subst([c[0]=1],SOL)$
y0:a*(1+subst(%,sum(c[k]*x^k,k,2,4)));

eq:ev(y0,x=1)=5;
solve(eq,a);

ev(y0,a=5.827,x=2);
powerdisp:false$

Print("======================================");
kill(all);
print("associated legendre equation");

declare(m,constant);
y:(1-x^2)^(m/2)*u(x);
diff(y,x,1);
diff(y,x,2);


Print("======================================");
kill(all);
print("Q 5.32");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,0,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,0,inf);

eq:x^2*Y2+4*x*Y1+(x^2+2)*Y;
expand(%);
intosum(%);
expand(%);

changevar(part(%,1),k-m-2,k,m)+changevar(part(%,2),k-m,k,m)+changevar(part(%,3),k-m,k,m)+changevar(part(%,4),k-m,k,m);
intosum(%);
sumcontract(%);
LHS:factorsum(%);
RHS:0;
REC:coeff(part(LHS,1,1),x,k+r);
RECA:coeff(part(LHS,2),x,r+1);
RECB:coeff(part(LHS,3),x,r);

rr:-1;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,2,6);

SOL:linsolve(%,makelist(c[k],k,2,6));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
x^rr*(1+subst(%,sum(c[k]*x^k,k,2,6)));
expand(%);
subst([c[0]=0,c[1]=1],SOL)$
x^rr*(x+subst(%,sum(c[k]*x^k,k,2,6)));
expand(%);
powerdisp:false$


kill(all);
eq:(x+2)^2*'diff(y,x,2)+(x+2)*'diff(y,x,1)-y=0;
ode2(eq,y,x);



Print("======================================");
kill(all);
print("Q 5.33");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,1,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,2,inf);

eq:x*Y2+2*Y1+x*Y;
expand(%);
intosum(%);
expand(%);

changevar(part(%,1),k-m-1,k,m)+changevar(part(%,2),k-m+1,k,m)+changevar(part(%,3),k-m+1,k,m);
intosum(%);
sumcontract(%);
LHS:factorsum(%);
RHS:0;
REC:coeff(part(LHS,1,1),x,k+r);
CON:0;
kk:expand(part(LHS,2));
kIND:factor(coeff(%,x,r));

RECA:subst(r=-1,REC);
makelist(subst(k=m,RECA)=0,m,1,6);
append(%,[CON=0]);
SOL:linsolve(%,makelist(c[k],k,2,7));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
x^(-1)*(1+subst(%,sum(c[k]*x^k,k,2,7)));
expand(%);
subst([c[0]=0,c[1]=1],SOL)$
x^(-1)*(x+subst(%,sum(c[k]*x^k,k,2,7)));
expand(%);
powerdisp:false$


kill(all);
eq:x*'diff(y,x,2)+2*'diff(y,x,1)+xy=0;
ode2(eq,y,x);


Print("======================================");
kill(all);
print("Q 5.34");

print("take X-1=x");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,0,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,0,inf);

eqa:x^2*'diff(y,x,2)-2*x*'diff(y,x)+2*y=0;

eq:x^2*Y2-2*x*Y1+2*Y;
expand(%);
intosum(%);
expand(%);
intosum(%);

changevar(%,k-m,k,m);
intosum(%);
sumcontract(%);
LHS:%;
RHS:0;
REC:coeff(part(LHS,1),x,k+r);

rr:2;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,1,6);

print("c1..c6 are zero so only c0 is left");

rr:1;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,1,6);

print("c1..c6 are zero so only c0 is left");

print("this shows the answers to be correct");
y:x^2;
eqa:x^2*diff(y,x,2)-2*x*diff(y,x)+2*y=0;
y:x^1;
eqa:x^2*diff(y,x,2)-2*x*diff(y,x)+2*y=0;


print("getting manual recurrence equations");
rr:2;
kREC:subst(r=rr,REC);
expand(%);

rr:1;
kREC:subst(r=rr,REC);
expand(%);



Print("======================================");
kill(all);
print("Q 5.35");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,1,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,2,inf);

eq:Y2+x*Y1+(1-2/(x^2))*Y;
expand(%);
intosum(%);
factorsum(%);

changevar(part(%,1),k-m,k,m)+changevar(part(%,2),k-m,k,m)+changevar(part(%,3),k-m+2,k,m)+changevar(part(%,4),k-m+2,k,m);
intosum(%);
sumcontract(%);
LHS:%;
RHS:0;

REC:coeff(part(LHS,1,1),x,k+r);
RECA:coeff(part(LHS,[2,3,4]),x,r);
RECB:coeff(part(LHS,5),x,r-1);
RECC:coeff(part(LHS,6),x,r-2);

rr:0;
kREC:subst(r=rr,REC);

kRECA:subst(r=rr,RECA);
kRECB:subst(r=rr,RECB);
kRECC:subst(r=rr,RECC);

makelist(subst(k=m,kREC)=0,m,5,10);
k:%;
SOL:linsolve(k,makelist(c[k],k,7,12));
powerdisp:true$
subst([c[5]=1,c[6]=0],SOL);
y0:x^rr*(1*x^5+subst(%,sum(c[k]*x^k,k,7,12)));
subst([c[5]=0,c[6]=1],SOL)$
y1:x^rr*(x^6+subst(%,sum(c[k]*x^k,k,7,12)));
powerdisp:false$

print("getting manual recurrence equations");
rr:-3;
kREC:subst(r=rr,REC);
expand(%);
print("this blows up at c_3");



rr:0;
kREC:subst(r=rr,REC);
expand(%);
factor(%);
print("this gives the correct coefficients");


y:1/x;
diff(y,x,2)+x*diff(y,x)+(1-2/(x^2))*y;


Print("======================================");
kill(all);
print("Q 5.36");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,0,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,0,inf);

eq:x*Y2+3*Y1+4*x^3*Y;
expand(%);
intosum(%);
expand(%);
intosum(%);

changevar(part(%,1),k-m-3,k,m)+changevar(part(%,2),k-m+1,k,m)+changevar(part(%,3),k-m+1,k,m);
intosum(%);
sumcontract(%);
LHS:%;
RHS:0;

REC:coeff(part(LHS,1,1),x,k+r);
RECA:coeff(part(LHS,[2,3]),x,r+2);
RECB:coeff(part(LHS,[4,5]),x,r+1);
RECC:coeff(part(LHS,[6,7]),x,r);
RECD:coeff(part(LHS,[8,9]),x,r-1);

rr:0;
kREC:subst(r=rr,REC);
kRECA:subst(r=rr,RECA);
kRECB:subst(r=rr,RECB);
kRECC:subst(r=rr,RECC);
kRECD:subst(r=rr,RECD);
makelist(subst(k=m,kREC)=0,m,3,9);
append(%,[kRECA=0]);
append(%,[kRECB=0]);
append(%,[kRECC=0]);
append(%,[kRECD=0]);
SOL:linsolve(%,makelist(c[k],k,1,10));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
x^rr*(1+subst(%,sum(c[k]*x^k,k,2,10)));
expand(%);
print("since c1 is actually zero so the second answer is not available");
powerdisp:false$

print("second solution");
rr:-2;
kREC:subst(r=rr,REC);
kRECA:subst(r=rr,RECA);
kRECB:subst(r=rr,RECB);
kRECC:subst(r=rr,RECC);
kRECD:subst(r=rr,RECD);
makelist(subst(k=m,kREC)=0,m,3,9);
append(%,[kRECA=0]);
append(%,[kRECB=0]);
append(%,[kRECC=0]);
append(%,[kRECD=0]);
SOL:linsolve(%,[c[1],c[3],c[4],c[5],c[6],c[7],c[8],c[9],c[10]]);

powerdisp:true$
subst([c[0]=1,c[2]=0],SOL)$
x^rr*(1+subst(%,sum(c[k]*x^k,k,3,10)));
expand(%);
subst([c[0]=0,c[2]=1],SOL)$
x^rr*(x^2+subst(%,sum(c[k]*x^k,k,3,10)));
expand(%);
powerdisp:false$

print("getting manual recurrence equations");
rr:0;
kREC:subst(r=rr,REC);
expand(%);

y:cos(x^2)/(x^2);
y:1/x*(1-4/15*x^4+16/(15*63)*x^8);
eq:x*diff(y,x,2)+3*diff(y,x)+4*x^3*y=0;



Print("======================================");
kill(all);
print("Q 5.37");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,0,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,0,inf);

eq:x^2*Y2-5*x*Y1+9*Y;
expand(%);
intosum(%);
expand(%);
intosum(%);

changevar(part(%,1),k-m,k,m)+changevar(part(%,2),k-m,k,m)+changevar(part(%,3),k-m,k,m);
intosum(%);
sumcontract(%);
LHS:%;
RHS:0;

REC:coeff(part(LHS,1,1),x,k+r)+coeff(part(LHS,1,2),x,k+r)+coeff(part(LHS,1,3),x,k+r);
kIND:subst(k=0,REC);
ksoln:solve(kIND,r);
ksol:map(rhs,ksoln);
rr:ksol[1];

kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,1,5);
SOL:linsolve(%,makelist(c[k],k,1,5));
powerdisp:true$
subst([c[0]=1],SOL)$
y1:x^rr*(1+subst(%,sum(c[k]*x^k,k,1,5)));
expand(%);
powerdisp:false$


print("getting manual recurrence equations");
rr:3;
kREC:subst(r=rr,REC);
expand(%);

print("checking answers by plugging back into differential equation");
y:y1;
eq:x^2*diff(y,x,2)-5*x*diff(y,x)+9*y=0;

y:x^3*log(x);
eq:x^2*diff(y,x,2)-5*x*diff(y,x)+9*y=0;
expand(%);



Print("======================================");
kill(all);
print("Q 5.38");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,0,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,0,inf);

eq:x*Y2+1*Y1-x*Y;
expand(%);
intosum(%);
expand(%);
intosum(%);

changevar(part(%,1),k-m-1,k,m)+changevar(part(%,2),k-m+1,k,m)+changevar(part(%,3),k-m+1,k,m);
intosum(%);
sumcontract(%);
LHS:%;
RHS:0;

REC:coeff(part(LHS,1,1),x,k+r);
kRECA:coeff(part(LHS,[2,3]),x,r);
kRECB:coeff(part(LHS,[4,5]),x,r-1);
kIND:kRECB;
ksoln:solve(kIND,r);
ksol:map(rhs,ksoln);
rr:ksol[1];

kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,1,8);
append(%,[subst(r=rr,kRECA)=0]);
SOL:linsolve(%,makelist(c[k],k,1,9));
powerdisp:true$
subst([c[0]=1],SOL)$
y1:x^rr*(1+subst(%,sum(c[k]*x^k,k,1,9)));
expand(%);
powerdisp:false$


print("getting manual recurrence equations");
rr:3;
kREC:subst(r=rr,REC);
expand(%);

print("checking answers by plugging back into differential equation");
y:y1;
eq:x^2*diff(y,x,2)-5*x*diff(y,x)+9*y=0;

y:x^3*log(x);
eq:x^2*diff(y,x,2)-5*x*diff(y,x)+9*y=0;
expand(%);


Print("======================================");
kill(all);
print("Q 5.39");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,0,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,0,inf);

eq:x^2*Y2+x*Y1-4*Y;
expand(%);
intosum(%);
expand(%);
intosum(%);

changevar(part(%,1),k-m,k,m)+changevar(part(%,2),k-m,k,m)+changevar(part(%,3),k-m,k,m);
intosum(%);
sumcontract(%);
LHS:%;
RHS:0;

REC:coeff(part(LHS,1,1),x,k+r)+coeff(part(LHS,1,2),x,k+r)+coeff(part(LHS,1,3),x,k+r);
kRECA:subst(k=0,REC);
kIND:kRECA;
ksoln:solve(kIND,r);
ksol:map(rhs,ksoln);
ra:ksol[2];
rb:ksol[1];

rr:ra;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,1,5);
SOL:linsolve(%,makelist(c[k],k,1,5));
powerdisp:true$
subst([c[0]=1],SOL)$
y1:x^rr*(1+subst(%,sum(c[k]*x^k,k,1,5)));
expand(%);
powerdisp:false$


rr:rb;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,1,5);
SOL:linsolve(%,makelist(c[k],k,1,5));

print("note that c4 cannot be calculated. it is actually not zero");
powerdisp:true$
subst([c[4]=1,c[0]=1],SOL)$
y1:x^rr*(c[0]+subst(%,sum(c[k]*x^k,k,1,5)));
expand(%);
powerdisp:false$



print("getting manual recurrence equations");
rr:3;
kREC:subst(r=rr,REC);
expand(%);

print("checking answers by plugging back into differential equation");
y:y1;
eq:x^2*diff(y,x,2)-5*x*diff(y,x)+9*y=0;

y:x^3*log(x);
eq:x^2*diff(y,x,2)-5*x*diff(y,x)+9*y=0;
expand(%);



Print("======================================");
kill(all);
print("Q 5.40");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,0,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,0,inf);

eq:x^2*Y2+6*x*Y1+(6-4*x^2)*Y;
expand(%);
intosum(%);
expand(%);
intosum(%);

changevar(part(%,1),k-m-2,k,m)+changevar(part(%,[2,3,4]),k-m,k,m);
intosum(%);
sumcontract(%);
LHS:%;
RHS:0;

REC:coeff(part(LHS,1,1),x,k+r);
kRECA:coeff(part(LHS,[2,3,4]),x,r+1);
kRECB:coeff(part(LHS,[5,6,7]),x,r);
kIND:kRECB;
ksoln:solve(kIND,r);
ksol:map(rhs,ksoln);
ra:ksol[2];
rb:ksol[1];

rr:ra;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,2,6);
append(%,[subst(r=rr,kRECA)=0]);
SOL:linsolve(%,makelist(c[k],k,1,6));
powerdisp:true$
subst([c[0]=1],SOL)$
y1:x^rr*(1+subst(%,sum(c[k]*x^k,k,1,6)));
expand(%);
powerdisp:false$


rr:rb;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,2,6);
append(%,[subst(r=rr,kRECA)=0]);
SOL:linsolve(%,makelist(c[k],k,2,6));

print("note that c1 cannot be calculated. it is actually not zero");
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
y1:x^rr*(1+subst(%,sum(c[k]*x^k,k,2,6)));
expand(%);
subst([c[0]=0,c[1]=1],SOL)$
y2:x^rr*(x+subst(%,sum(c[k]*x^k,k,2,6)));
expand(%);
powerdisp:false$


print("taylor series of the answers");
taylor(sinh(2*x)/(x^3),x,0,6);
taylor(cosh(2*x)/(x^3),x,0,6);

print("getting manual recurrence equations");
rr:3;
kREC:subst(r=rr,REC);
expand(%);

print("checking answers by plugging back into differential equation");
y:y1;
eq:x^2*diff(y,x,2)-5*x*diff(y,x)+9*y=0;

y:cosh(2*x)/(x^3);
eq:x^2*diff(y,x,2)+6*x*diff(y,x)+(6-4*x^2)*y=0;
expand(%);



Print("======================================");
kill(all);
print("Q 5.41");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,0,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,0,inf);

eq:x*Y2+(1-2*x)*Y1+(x-1)*Y;
expand(%);
intosum(%);
expand(%);
factorsum(%);
intosum(%);
TOT:%;
changevar(part(TOT,1),k-m-1,k,m)+changevar(part(TOT,[2,3]),k-m,k,m)+changevar(part(TOT,[4,5]),k-m+1,k,m);
intosum(%);
sumcontract(%);
LHS:%;
RHS:0;

REC:coeff(part(LHS,1,1),x,k+r);
kRECA:coeff(part(LHS,[2,3,4,5]),x,r);
kRECB:coeff(part(LHS,[6,7]),x,r-1);
kIND:kRECB;
ksoln:solve(kIND,r);
ksol:map(rhs,ksoln);
ra:ksol[1];
rb:ksol[1];

rr:ra;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,1,6);
append(%,[subst(r=rr,kRECA)=0]);
append(%,[subst(r=rr,kRECB)=0]);
SOL:linsolve(%,makelist(c[k],k,1,7));
powerdisp:true$
subst([c[0]=1],SOL)$
y1:x^rr*(1+subst(%,sum(c[k]*x^k,k,1,6)));
expand(%);
powerdisp:false$


Print("======================================");
kill(all);
print("Q 5.43");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,0,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,0,inf);

eq:Y2+0*Y1+(x-1)*Y;
expand(%);
intosum(%);
expand(%);
factorsum(%);
intosum(%);
TOT:%;
changevar(part(TOT,1),k-m-1,k,m)+changevar(part(TOT,2),k-m,k,m)+changevar(part(TOT,3),k-m+2,k,m);
intosum(%);
sumcontract(%);
LHS:%;
RHS:0;

REC:coeff(part(LHS,1,1),x,k+r);
kRECA:coeff(part(LHS,[2,3]),x,r);
kRECB:coeff(part(LHS,[4]),x,r-1);
kIND:kRECB;
ksoln:solve(kIND,r);
ksol:map(rhs,ksoln);
ra:ksol[2];
rb:ksol[1];

rr:ra;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,1,6);
append(%,[subst(r=rr,kRECA)=0]);
append(%,[subst(r=rr,kRECB)=0]);
SOL:linsolve(%,makelist(c[k],k,2,8));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
y1:x^rr*(1+subst(%,sum(c[k]*x^k,k,2,6)));
expand(%);
subst([c[0]=0,c[1]=1],SOL)$
y2:x^rr*(x+subst(%,sum(c[k]*x^k,k,2,6)));
expand(%);
powerdisp:false$


Print("======================================");
kill(all);
print("Q 5.44");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,0,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,0,inf);

eq:x*Y2+(2-2*x)*Y1+(x-2)*Y;
expand(%);
intosum(%);
expand(%);
factorsum(%);
intosum(%);
TOT:%;
changevar(part(TOT,1),k-m-1,k,m)+changevar(part(TOT,2),k-m,k,m)+changevar(part(TOT,[3,4]),k-m+1,k,m);
intosum(%);
sumcontract(%);
LHS:%;
RHS:0;

REC:coeff(part(LHS,1,1),x,k+r);
kRECA:coeff(part(LHS,[2,3,4]),x,r);
kRECB:coeff(part(LHS,[5,6]),x,r-1);
kIND:kRECB;
ksoln:solve(kIND,r);
ksol:map(rhs,ksoln);
ra:ksol[2];
rb:ksol[1];

rr:ra;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,1,6);
append(%,[subst(r=rr,kRECA)=0]);
append(%,[subst(r=rr,kRECB)=0]);
SOL:linsolve(%,makelist(c[k],k,1,7));
powerdisp:true$
subst([c[0]=1],SOL)$
y1:x^rr*(1+subst(%,sum(c[k]*x^k,k,1,6)));
expand(%);
powerdisp:false$



rr:rb;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,1,6);
append(%,[subst(r=rr,kRECA)=0]);
append(%,[subst(r=rr,kRECB)=0]);
SOL:linsolve(%,makelist(c[k],k,2,7));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
y1:x^rr*(1+subst(%,sum(c[k]*x^k,k,2,6)));
expand(%);
subst([c[0]=0,c[1]=1],SOL)$
y2:x^rr*(x+subst(%,sum(c[k]*x^k,k,2,6)));
expand(%);
powerdisp:false$


y:%e^x;
x*diff(y,x,2)+(2-2*x)*diff(y,x,1)+(x-2)*y=0;
expand(%);


y:1/x*%e^x;
x*diff(y,x,2)+(2-2*x)*diff(y,x,1)+(x-2)*y=0;
expand(%);

Print("======================================");
kill(all);
print("Q 5.55");

powerdisp:false;

Y:sum(c[m]*x^(m+r),m,0,inf);
Y1:sum((m+r)*c[m]*x^(m+r-1),m,0,inf);
Y2:sum((m+r)*(m+r-1)*c[m]*x^(m+r-2),m,0,inf);

eq:2*x*(1-x)*Y2-(1+5*x)*Y1-1*Y;
expand(%);
intosum(%);
expand(%);
factorsum(%);
intosum(%);
TOT:%;
changevar(part(TOT,[1,2,3]),k-m,k,m)+changevar(part(TOT,[4,5]),k-m+1,k,m);
intosum(%);
sumcontract(%);
LHS:%;
RHS:0;

REC:coeff(part(LHS,1,1),x,k+r);
kRECA:coeff(part(LHS,[2,3]),x,r-1);
kIND:kRECA;
ksoln:solve(kIND,r);
ksol:map(rhs,ksoln);
ra:ksol[1];
rb:ksol[2];

rr:ra;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,0,6);
append(%,[subst(r=rr,kRECA)=0]);
SOL:linsolve(%,makelist(c[k],k,1,7));
powerdisp:true$
subst([c[0]=1],SOL)$
y1:x^rr*(1+subst(%,sum(c[k]*x^k,k,1,6)));
expand(%);
powerdisp:false$


rr:rb;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,0,6);
append(%,[subst(r=rr,kRECA)=0]);
SOL:linsolve(%,makelist(c[k],k,1,7));
powerdisp:true$
subst([c[0]=1],SOL)$
y1:x^rr*(1+subst(%,sum(c[k]*x^k,k,1,6)));
expand(%);
powerdisp:false$

rr:rb;
kREC:subst(r=rr,REC);
makelist(subst(k=m,kREC)=0,m,1,6);
append(%,[subst(r=rr,kRECA)=0]);
append(%,[subst(r=rr,kRECB)=0]);
SOL:linsolve(%,makelist(c[k],k,2,7));
powerdisp:true$
subst([c[0]=1,c[1]=0],SOL)$
y1:x^rr*(1+subst(%,sum(c[k]*x^k,k,2,6)));
expand(%);
subst([c[0]=0,c[1]=1],SOL)$
y2:x^rr*(x+subst(%,sum(c[k]*x^k,k,2,6)));
expand(%);
powerdisp:false$

a:1;
b:1/2;
c:-1/2;
F1:1+sum(product((a+i)*(b+i)/((c+i)),i,0,k)*x^(k+1)/(k+1)!,k,0,3);

a:5/2;
b:2;
c:5/2;
F2:x^(1-c)*(1+sum(product((a+i)*(b+i)/((c+i)),i,0,k)*x^(k+1)/(k+1)!,k,0,3));

Print("======================================");
kill(all);
print("Q 5.55a");

powerdisp:true;

a:1;
b:1/2;
c:-1/2;
F1:1+sum(product((a+i)*(b+i)/((c+i)),i,0,k)*x^(k+1)/(k+1)!,k,0,3);

a:5/2;
b:2;
c:5/2;
F2:x^(1-c)*(1+sum(product((a+i)*(b+i)/((c+i)),i,0,k)*x^(k+1)/(k+1)!,k,0,3));
powerdisp:false;


print("=======================");
kill(all);
print("Q 5.60");
print("this turns a standard bessel's equation into the question Q to be given to the student");
print("in eqb interchange x and z and give this as additional information in the question");

v:0;
depends(y,z);
eqa:z(x):=2*x;
eqb:x=z/2;  

yDk:diff(z(x),x)*'diff(y,z);
yD:subst(eqb,%);
yDDk:diff(yD,z)*diff(z(x),x);
yDD:subst(eqb,%);

eq:x^2*yDD+x*yD+(x^2-v^2)*y=0;
subst(eqb,%);
expand(%);


print("=======================");
kill(all);
print("Q 5.62");
print("this turns a standard bessel's equation into the question Q to be given to the student");
print("in eqb interchange x and z and give this as additional information in the question");

v:1/3;
depends(y,z);
eqa:z(x):=3*x;
eqb:x=z/3;  

yDk:diff(z(x),x)*'diff(y,z);
yD:subst(eqb,%);
yDDk:diff(yD,z)*diff(z(x),x);
yDD:subst(eqb,%);

eq:x^2*yDD+x*yD+(x^2-v^2)*y=0;
subst(eqb,%);
expand(%);

print("=======================");
kill(all);
print("Q 5.63");
print("this turns a standard bessel's equation into the question Q to be given to the student");
print("in eqb interchange x and z and give this as additional information in the question");

v:4;
depends(y,z);
eqa:z(x):=log(x);
eqb:x=%e^z;  

yDk:diff(z(x),x)*'diff(y,z);
yD:subst(eqb,%);
yDDk:diff(yD,z)*diff(z(x),x);
yDD:subst(eqb,%);

eq:x^2*yDD+x*yD+(x^2-v^2)*y=0;
subst(eqb,%);
expand(%);


print("=======================");
kill(all);
print("Q 5.64");
print("this turns a standard bessel's equation into the question Q to be given to the student");
print("in eqb interchange x and z and give this as additional information in the question");

declare([v,L],constant);

depends(y,z);
eqa:z(x):=x/L;
eqb:x=z*L;  

yDk:diff(z(x),x)*'diff(y,z);
yD:subst(eqb,%);
yDDk:diff(yD,z)*diff(z(x),x);
yDD:subst(eqb,%);

eq:x^2*yDD+x*yD+(x^2-v^2)*y=0;
subst(eqb,%);
expand(%);


print("=======================");
kill(all);
print("Q 5.65");
print("this turns a standard bessel's equation into the question Q to be given to the student");
print("in eqb interchange x and z and give this as additional information in the question");

declare([v,L],constant);
v:1;

depends(y,z);
eqa:z(x):=x/3;
eqb:x=z*3;  

yDk:diff(z(x),x)*'diff(y,z);
yD:subst(eqb,%);
yDDk:diff(yD,z)*diff(z(x),x);
yDD:subst(eqb,%);

eq:x^2*yDD+x*yD+(x^2-v^2)*y=0;
subst(eqb,%);
expand(%);


print("=======================");
kill(all);
print("Q 5.66");
print("this turns a standard bessel's equation into the question Q to be given to the student");
print("in eqb interchange x and z and give this as additional information in the question");

declare([v,L],constant);
v:1;

depends(y,z);
eqa:z(x):=x/2+1/2;
eqb:x=2*z-1;  

yDk:diff(z(x),x)*'diff(y,z);
yD:subst(eqb,%);
yDDk:diff(yD,z)*diff(z(x),x);
yDD:subst(eqb,%);

eq:x^2*yDD+x*yD+(x^2-v^2)*y=0;
subst(eqb,%);
expand(%);


print("=======================");
kill(all);
print("Q 5.83");
print("this turns a standard bessel's equation into the question Q to be given to the student");
print("in eqb interchange x and z and give this as additional information in the question");

v:3/2;
depends(y,z);
eqa:z(x):=x^3;
eqb:x=z^(1/3);  

yDk:diff(z(x),x)*'diff(y,z);
yD:subst(eqb,%);
yDDk:diff(yD,z)*diff(z(x),x);
yDD:subst(eqb,%);

eq:x^2*yDD+x*yD+(x^2-v^2)*y=0;
subst(eqb,%);
expand(%);


print("=======================");
kill(all);
print("Q 5.84");
print("this turns a standard bessel's equation into the question Q to be given to the student");
print("in the questin given, x is written instead of z");
print("in eqb interchange x and z and give this as additional information in the question");

v:2/3;
depends(y,z);
eqa:z(x):=sqrt(x);
eqb:x=z^2;  

yDk:diff(z(x),x)*'diff(y,z);
yD:subst(eqb,%);
yDDk:diff(yD,z)*diff(z(x),x);
yDD:subst(eqb,%);

eq:x^2*yDD+x*yD+(x^2-v^2)*y=0;
subst(eqb,%);
Q:expand(%);


print("=======================");
kill(all);
print("Q 5.85");
print("this turns a standard bessel's equation into the question Q to be given to the student");
print("in the questin given, x is written instead of z");
print("in eqb interchange x and z and give this as additional information in the question");

v:5/2;
depends(y,z);
eqa:z(x):=x^(3/2);
eqb:x=z^(2/3);  

yDk:diff(z(x),x)*'diff(y,z);
yD:subst(eqb,%);
yDDk:diff(yD,z)*diff(z(x),x);
yDD:subst(eqb,%);

eq:x^2*yDD+x*yD+(x^2-v^2)*y=0;
subst(eqb,%);
Q:expand(%);




print("=======================");
kill(all);
print("QQ 9.1");

declare(n,integer);
f:cos(x);
a:0;
b:2*%pi;

n:sqrt(integrate(f*f,x,a,b));

print("=======================");
kill(all);
print("QQ 9.2");

declare(n,integer);
f:sin(n*x);
a:0;
b:1*%pi;

n:sqrt(integrate(f*f,x,a,b));

print("=======================");
kill(all);
print("QQ 9.3");

declare(n,integer);
f:sin(n*%pi*x);
a:-1;
b:1;

n:sqrt(integrate(f*f,x,a,b));

print("=======================");
kill(all);
print("QQ 9.4");

declare(n,integer);
fa:1;
f:cos(2*n*x);
a:0;
b:%pi;

na:n:sqrt(integrate(fa*fa,x,a,b));
n:sqrt(integrate(f*f,x,a,b));

print("=======================");
kill(all);
print("QQ 9.5");

declare(n,integer);
fa:1;
f:cos(2*n*%pi*x/T);
a:0;
b:T;

na:n:sqrt(integrate(fa*fa,x,a,b));
n:sqrt(integrate(f*f,x,a,b));

print("=======================");
kill(all);
print("QQ 9.6");

declare(n,integer);
f:sin(2*n*%pi*x/T);
a:-T/2;
b:T/2;

n:sqrt(integrate(f*f,x,a,b));

print("=======================");
kill(all);
print("QQ 9.7");
load(orthopoly);

P00(x);


print("=======================");
kill(all);
print("QQ 9.18");

assume(a>0);
eq:'diff(y,x,2)+a*y=0;
ode2(eq,y,x);
bc2(%,x=0,'diff(y,x)=0,x=l,'diff(y,x)=0);

print("=======================");
kill(all);
print("QQ 9.23");
load(orthopoly);

legendre_p(3,x);

kone:legendre_p(0,x);
kx:legendre_p(1,x);
kx2:1/3*legendre_p(0,x)+2/3*legendre_p(2,x);
ratsimp(%);
kx3:3/5*legendre_p(1,x)+2/5*legendre_p(3,x);
ratsimp(%);
kx4:1/5*legendre_p(0,x)+4/7*legendre_p(2,x)+8/35*legendre_p(4,x);
ratsimp(%);


2*legendre_p(2,x)+2*legendre_p(1,x)+legendre_p(0,x);
ratsimp(%);
