Print("======================================");
kill(all);
print("Q 18.36");

f:sin(z^2);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5];



Print("======================================");
kill(all);
print("Q 18.37");

f:%e^(-z);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5];



Print("======================================");
kill(all);
print("Q 18.38");

f:%e^z;
a:1;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5];




Print("======================================");
kill(all);
print("Q 18.39");

f:%e^z;
a:%i*%pi;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5];


Print("======================================");
kill(all);
print("Q 18.40");

f:sin(z);
a:%pi/2;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7];

Print("======================================");
kill(all);
print("Q 18.41");

f:cos(z);
a:-%pi/4;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5];


Print("======================================");
kill(all);
print("Q 18.42");

f:1/(1-z);
a:-1;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5];

n:100;
(1/(2^(n+1)))^(1/n);
L:float(%);
R:1/L;

kill(all);
L:limit(1/(2^(n/(n+1))),n,inf);
R:1/L;

Print("======================================");
kill(all);
print("Q 18.43");

f:1/z;
a:-1;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5];


Print("======================================");
kill(all);
print("Q 18.44");

f:1/(1-z);
a:%i;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5];

kill(all);
L:limit((abs(1/(1-%i)))^((n+1)/n),n,inf);
R:1/L;


Print("======================================");
kill(all);
print("Q 18.45");

f:cos(z)*cos(z);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5];


Print("======================================");
kill(all);
print("Q 18.46");

f:sin(z)^2;
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7];



Print("======================================");
kill(all);
print("Q 18.47");

f:tan(z);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7];



Print("======================================");
kill(all);
print("Q 18.48");

f:%e^z*sin(z);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

display[b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7];


Print("======================================");
kill(all);
print("Q 18.50");

f:(%e^z-1);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

ff:1/z*(b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7);

integrate(ff,z,0,zz);
expand(%);


Print("======================================");
kill(all);
print("Q 18.51");

f:1-cos(z);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

ff:1/z^2*(b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7);

integrate(ff,z,0,zz);
expand(%);



Print("======================================");
kill(all);
print("Q 18.52");

f:%e^(-z^2);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7;

2/sqrt(%pi)*integrate(ff,z,0,zz);
expand(%);


Print("======================================");
kill(all);
print("Q 18.53");

f:sin(z);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;

ff:1/z*(b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7);

integrate(ff,z,0,zz);
expand(%);



Print("======================================");
kill(all);
print("Q 18.54");

f:sin(z^2);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;

integrate(ff,z,0,zz);
expand(%);


Print("======================================");
kill(all);
print("Q 18.55");

f:cos(z^2);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;

integrate(ff,z,0,zz);
expand(%);

Print("======================================");
kill(all);
print("example 18.13");

c:(-1)^n*(n+1)/(3^(n+2))-1/(2^n);
ev(c,n=0);
ev(c,n=1);
ev(c,n=2);


Print("======================================");
kill(all);
print("Q 18.60");

f:(4*z^2+30*z+68)/((z+4)^2*(z-2));
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;


Print("======================================");
kill(all);
print("Q 18.61");

f:cos(z^2);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;



Print("======================================");
kill(all);
print("Q 18.62");

f:%e^(z^2-z);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;


Print("======================================");
kill(all);
print("Q 18.63");

f:%e^(z^4);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;



Print("======================================");
kill(all);
print("Q 18.64");

f:cos(z)/(1-z^2);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;



Print("======================================");
kill(all);
print("Q 18.65");

f:%e^(z^2)*sin(z^2);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;





Print("======================================");
kill(all);
print("Q 18.66");

f:%e^(z^2)/cos(z);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;


Print("======================================");
kill(all);
print("Q 18.67");

f:%e^(1/(1-z));
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;


Print("======================================");
kill(all);
print("Q 18.68");

f:cos(z/(1-z));
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;


Print("======================================");
kill(all);
print("Q 18.69");

f:%e^(%e^z);
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;


Print("======================================");
kill(all);
print("Q 18.70");

f:1/(2*z-%i);
a:-1;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;



Print("======================================");
kill(all);
print("Q 18.71");

f:1/(4-3*z);
a:1+%i;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;


Print("======================================");
kill(all);
print("Q 18.72");

f:(2-3*z)/(2*z^2-3*z+1);
a:-1;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;


Print("======================================");
kill(all);
print("Q 18.73");

f:1/(1+z)^2;
a:-%i;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;


Print("======================================");
kill(all);
print("Q 18.74");

f:1/(2+3*z^3)^2;
a:0;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;


Print("======================================");
kill(all);
print("Q 18.75");

f:tan(z);
a:%pi/4;
n:0;
diff(f,z,n);
b0:ev(%,z=a)/n!;
n:1;
diff(f,z,n);
b1:ev(%,z=a)/n!;
n:2;
diff(f,z,n);
b2:ev(%,z=a)/n!;
n:3;
diff(f,z,n);
b3:ev(%,z=a)/n!;
n:4;
diff(f,z,n);
b4:ev(%,z=a)/n!;
n:5;
diff(f,z,n);
b5:ev(%,z=a)/n!;
n:6;
diff(f,z,n);
b6:ev(%,z=a)/n!;
n:7;
diff(f,z,n);
b7:ev(%,z=a)/n!;
n:8;
diff(f,z,n);
b8:ev(%,z=a)/n!;
n:9;
diff(f,z,n);
b9:ev(%,z=a)/n!;
n:10;
diff(f,z,n);
b10:ev(%,z=a)/n!;
n:11;
diff(f,z,n);
b11:ev(%,z=a)/n!;

ff:b0*(z-a)^0+b1*(z-a)^1+b2*(z-a)^2+b3*(z-a)^3+b4*(z-a)^4+b5*(z-a)^5+b6*(z-a)^6+b7*(z-a)^7+b8*(z-a)^8+b9*(z-a)^9+b10*(z-a)^(10)+b11*(z-a)^11;

